name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build and push
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build . --tag ltrump/cqmirai:latest
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        docker push ltrump/cqmirai:latest
