name: Release
on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v1
    - uses: olegtarasov/get-tag@v2
      id: tagName
    - name: build and push
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build . --tag ltrump/cqmirai:$GIT_TAG_NAME
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        docker push ltrump/cqmirai:$GIT_TAG_NAME
